name: Deploy

on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare deployment
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DEPLOY_SERVER_IP: ${{ secrets.DEPLOY_SERVER_IP }}
        run: |
             mkdir -p ~/.ssh
             chmod 700 ~/.ssh
             echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
             chmod 600 ~/.ssh/id_rsa
             ssh-keyscan -t rsa $DEPLOY_SERVER_IP >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          DEPLOY_SERVER_IP: ${{ secrets.DEPLOY_SERVER_IP }}
          DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: ssh -t $DEPLOY_USER@$DEPLOY_SERVER_IP "cd $DEPLOY_DIR && git checkout . && git checkout main && git fetch --all && git reset --hard origin/main && git pull && sed -i 's/USER/$DEPLOY_USER/' crypto_alert_bot.service && sudo cp crypto_alert_bot.service /etc/systemd/system/ && sudo systemctl daemon-reload && sudo systemctl enable crypto_alert_bot && ls -lh data log && sudo systemctl restart crypto_alert_bot && sleep 20 && systemctl status crypto_alert_bot && tail log/info.log"
